### ISSUE TITLE
help with migration problem - django 1.9 - ImportError: cannot import name ReverseManyRelatedObjectsDescriptor

### ISSUE THREAD

**Issue by jonathanmorgan** [burke-software/django-report-utils#22]
Hello,

Testing out django 1.9, when I run migrations for django-report-utils, I get the following error:

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
        utility.execute()
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
        self.check()
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
        include_deployment_checks=include_deployment_checks,
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
        return check_resolver(resolver)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
        for pattern in resolver.url_patterns:
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
        return import_module(self.urlconf_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/jonathanmorgan/Documents/work/cvnc/django-apps/cvnc/cvnc/urls.py", line 29, in <module>
        url( r'^report_builder/', include( 'report_builder.urls' ) ),
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
        urlconf_module = import_module(urlconf_module)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/report_builder/urls.py", line 4, in <module>
        from . import views
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/report_builder/views.py", line 18, in <module>
        from report_utils.mixins import DataExportMixin, generate_filename
      File "/home/jonathanmorgan/.virtualenvs/cvnc/local/lib/python2.7/site-packages/report_utils/mixins.py", line 5, in <module>
        from django.db.models.fields.related import ReverseManyRelatedObjectsDescriptor
    ImportError: cannot import name ReverseManyRelatedObjectsDescriptor

I read here:

https://github.com/swisscom/cleanerversion/issues/111

that this class is among the ones that have been refactored into a new package:

> In django.db.models.fields.related, the members ReverseSingleRelatedObjectDescriptor, ReverseManyRelatedObjectsDescriptor, ManyRelatedObjectsDescriptor, create_many_related_manager, ForeignRelatedObjectsDescriptor have been refactored into new classes at django.db.models.fields.related_descriptors.

I tried updating the mixins.py file so that it references `django.db.models.fields.related_descriptors` rather than `django.db.models.fields.related`, but that didn't fix it.  So, not sure if that is it or not.  I looked in the release notes for 1.9 and didn't see any mention of this...

Any advice on what might be causing this or what I can do to fix it would be greatly appreciated.

Thanks,

Jonathan Morgan

**Comment by willseward** [comment]
I'll put in a PR

**Comment by willseward** [comment]
https://github.com/burke-software/django-report-utils/pull/23

**Comment by bufke** [comment]
I'm considering just moving the few remaining functions used here to django-report-builder. This repo was shared with django-admin-export but I'm not maintaining that now and it never got popular. Any objections?

**Comment by grantjenks** [comment]
@bufke I think that's a great idea. Please do.

In doing so, please do not pull django-report-utils from PyPI. I have clients still using older versions.

**Comment by bufke** [comment]
Yep makes sense.

**Comment by bufke** [comment]
Someone just asked me about supporting admin export. I'm going to see if they are willing to pay for it. For now the pull request is accepted. In any case the existing versions of report utils will stay on pypi.

**Comment by bufke** [comment]
Now on pypi. Will consider moving the functions to report builder later. New report builder should be up as soon.
